// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyB35MiUXeiNGRSF3BRpui-GZxmSr6iak2I',
  //   appId: '1:228686973014:web:07e841a945b09d6bfd13f7',
  //   messagingSenderId: '228686973014',
  //   projectId: 'yuukidatabase-a715b',
  //   authDomain: 'yuukidatabase-a715b.firebaseapp.com',
  //   storageBucket: 'yuukidatabase-a715b.appspot.com',
  //   measurementId: 'G-R0FZKP1KXY',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDARHDIaWGd9hA6m3XY-Eqt1HOdV6dLiX4',
    appId: '1:126628150865:android:6e594846fe882ca2ccc270',
    messagingSenderId: '126628150865',
    projectId: 'store-master-dinnblack',
    storageBucket: 'store-master-dinnblack.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCuZCD7BdBQK5tMXB5YkMiyb2Z3Jwl7thM',
  //   appId: '1:228686973014:ios:bc8b7196e748a61efd13f7',
  //   messagingSenderId: '228686973014',
  //   projectId: 'yuukidatabase-a715b',
  //   storageBucket: 'yuukidatabase-a715b.appspot.com',
  //   iosBundleId: 'com.example.yuuki',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyCuZCD7BdBQK5tMXB5YkMiyb2Z3Jwl7thM',
  //   appId: '1:228686973014:ios:185ea1429d5c0dbefd13f7',
  //   messagingSenderId: '228686973014',
  //   projectId: 'yuukidatabase-a715b',
  //   storageBucket: 'yuukidatabase-a715b.appspot.com',
  //   iosBundleId: 'com.example.yuuki.RunnerTests',
  // );
}
